version: 0.2
phases:
  build:
    commands:
      - aws cloudformation package --template-file sam.yaml --s3-bucket $S3_BUCKET
                                   --output-template-file out_sam.yaml
artifacts:
  type: zip
  files:
    - out_sam.yaml