AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Post pipeline state to Slack
Parameters:
  SlackWebhookUrl:
    Type: String
  SlackUserName:
    Type: String
    Default: ""
  SlackIconUrl:
    Type: String
    Default: ""
  SlackIconEmoji:
    Type: String
    Default: ""
  TargetState:
    Type: CommaDelimitedList
    Default: CANCELED,FAILED,RESUMED,STARTED,SUCCEEDED
Resources:
  postPipelineStateToSlack:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./src
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: !Ref SlackWebhookUrl
          SLACK_USER_NAME: !Ref SlackUserName
          SLACK_ICON_URL: !Ref SlackIconUrl
          SLACK_ICON_EMOJI: !Ref SlackIconEmoji
      Events:
        ScheduleEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - 'aws.codepipeline'
              detail-type:
                - CodePipeline Stage Execution State Change
              detail:
                state: !Ref TargetState